### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'get'

### ISSUE THREAD

**Issue by EdgarEspitia** [ec-jrc/lisflood-utilities#35]
Dear Lisflood community,

Today I have updated the lisflood-utilities and I when I try to use the cutmaps, threshold and waterregions tools I get the error message:
`AttributeError: 'EntryPoints' object has no attribute 'get'`

Error output of running the waterregions scripts [error_lisflood_utilities.txt](https://github.com/ec-jrc/lisflood-utilities/files/11465408/error_lisflood_utilities.txt)

Please advise on how to fix this problem.

Thanks in advance!
Edgar

**Comment by doc78** [comment]
Dear Edgar
This is probably caused by a new version of the package importlib-metadata. Please check the version of this package by typing pip list. If the version is 5 or more, you can fix this issue by running "pip install importlib-metadata<5.0.0" or "pip install importlib-metadata==4.2.0" that is the version tested in our environments.
Hope this will solve the issue.
Cheers
Carlo

**Comment by EdgarEspitia** [comment]
Dear Carlo,
It works.
Thank you vey much!
Edgar
